"""
Generate INSERT scripts for all metadata tables from local DB.
Run: python3 generate_insert_scripts.py
Output: db_scripts/METADATA_INSERT.sql  (ready to run on cloud DB)
"""

import os
import sys
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

# ── DB connection (local Oracle XE — no wallet) ───────────────
import oracledb

conn = oracledb.connect(
    user="system",
    password="Oracle123",
    dsn="localhost:1521/XEPDB1",
)

print("✅ Connected to DB")

cursor = conn.cursor()

# ── Metadata tables to export (skip transactional data) ───────
METADATA_TABLES = [
    "products",
    "product_variants",
    "pricing",
    "stock_inventory",
    "locations",
    "pickup_locations",
    "admin_users",
    "spoc_contacts",
]

output_lines = []
output_lines.append("-- ============================================================")
output_lines.append("-- METADATA INSERT SCRIPT")
output_lines.append(f"-- Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
output_lines.append("-- Tables: " + ", ".join(METADATA_TABLES))
output_lines.append("-- ============================================================")
output_lines.append("")


def quote_value(val):
    """Convert a Python value to Oracle SQL literal."""
    if val is None:
        return "NULL"
    if isinstance(val, str):
        escaped = val.replace("'", "''")
        return f"'{escaped}'"
    if isinstance(val, datetime):
        return f"TIMESTAMP '{val.strftime('%Y-%m-%d %H:%M:%S.%f')}'"
    return str(val)


for table in METADATA_TABLES:
    print(f"  Reading {table}...", end=" ")

    # Get column names (excluding IDENTITY columns — we use OVERRIDING SYSTEM VALUE)
    cursor.execute(f"SELECT * FROM {table} WHERE 1=0")
    columns = [d[0].lower() for d in cursor.description]

    # Fetch all rows
    cursor.execute(f"SELECT * FROM {table}")
    rows = cursor.fetchall()
    print(f"{len(rows)} rows")

    output_lines.append(f"-- ------------------------------------------------------------")
    output_lines.append(f"-- {table.upper()} ({len(rows)} rows)")
    output_lines.append(f"-- ------------------------------------------------------------")

    if not rows:
        output_lines.append(f"-- (no data)")
        output_lines.append("")
        continue

    col_list = ", ".join(columns)

    # Allow explicit ID inserts on IDENTITY columns
    output_lines.append(f"ALTER TABLE {table} MODIFY id GENERATED BY DEFAULT AS IDENTITY;")

    for row in rows:
        values = ", ".join(quote_value(v) for v in row)
        output_lines.append(f"INSERT INTO {table} ({col_list}) VALUES ({values});")

    output_lines.append("COMMIT;")
    # Restore strict IDENTITY after inserts
    output_lines.append(f"ALTER TABLE {table} MODIFY id GENERATED ALWAYS AS IDENTITY;")
    output_lines.append("")


# ── Write output file ──────────────────────────────────────────
out_path = os.path.join(os.path.dirname(__file__), "db_scripts", "METADATA_INSERT.sql")
with open(out_path, "w", encoding="utf-8") as f:
    f.write("\n".join(output_lines))

cursor.close()
conn.close()

print(f"\n✅ Script written to: {out_path}")
print("   Run it on the cloud DB using SQL*Plus or SQLDeveloper.")
