-- Garden Roots Oracle Database Schema
-- Main database tables for product catalog, inventory, orders, and customer management

-- Create PRODUCTS table (Core product information)
CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL UNIQUE,
    description VARCHAR2(500),
    origin VARCHAR2(150),
    season_start VARCHAR2(10),
    season_end VARCHAR2(10),
    tag VARCHAR2(50),
    created_at TIMESTAMP DEFAULT SYSDATE,
    updated_at TIMESTAMP DEFAULT SYSDATE
);

-- Create PRODUCT_VARIANTS table (Packaging/size options)
CREATE TABLE product_variants (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    size_name VARCHAR2(100) NOT NULL,
    unit VARCHAR2(50) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSDATE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    UNIQUE(product_id, size_name)
);

-- Create PRICING table (Dynamic pricing by variant & date)
CREATE TABLE pricing (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_variant_id NUMBER NOT NULL,
    base_price DECIMAL(10, 2) NOT NULL,
    currency VARCHAR2(10) DEFAULT 'USD',
    valid_from DATE,
    valid_to DATE,
    created_at TIMESTAMP DEFAULT SYSDATE,
    updated_at TIMESTAMP DEFAULT SYSDATE,
    FOREIGN KEY (product_variant_id) REFERENCES product_variants(id) ON DELETE CASCADE
);

-- Create STOCK_INVENTORY table (Real-time stock levels)
CREATE TABLE stock_inventory (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_variant_id NUMBER NOT NULL,
    quantity_available NUMBER DEFAULT 0 NOT NULL,
    reserved_quantity NUMBER DEFAULT 0,
    warehouse_location VARCHAR2(200),
    last_updated TIMESTAMP DEFAULT SYSDATE,
    FOREIGN KEY (product_variant_id) REFERENCES product_variants(id) ON DELETE CASCADE,
    UNIQUE(product_variant_id)
);

-- Create LOCATIONS table (Pickup locations)
CREATE TABLE locations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_name VARCHAR2(150) NOT NULL,
    address VARCHAR2(300) NOT NULL,
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    operating_hours VARCHAR2(100),
    created_at TIMESTAMP DEFAULT SYSDATE
);

-- Create ORDERS table (Order tracking)
CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_ref VARCHAR2(50) UNIQUE NOT NULL,
    customer_name VARCHAR2(150) NOT NULL,
    customer_email VARCHAR2(150),
    customer_phone VARCHAR2(20),
    subtotal DECIMAL(10, 2) NOT NULL,
    delivery_fee DECIMAL(10, 2) DEFAULT 0,
    total_price DECIMAL(10, 2) NOT NULL,
    payment_method VARCHAR2(50),
    payment_status VARCHAR2(50) DEFAULT 'pending',
    payment_intent_id VARCHAR2(300),
    order_status VARCHAR2(50) DEFAULT 'pending',
    delivery_address VARCHAR2(500),
    created_at TIMESTAMP DEFAULT SYSDATE,
    updated_at TIMESTAMP DEFAULT SYSDATE
);

-- Create ORDER_ITEMS table (Line items in each order)
CREATE TABLE order_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    product_variant_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    unit_price DECIMAL(10, 2) NOT NULL,
    subtotal DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSDATE,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (product_variant_id) REFERENCES product_variants(id)
);

-- Create indexes for performance optimization
CREATE INDEX idx_products_name ON products(name);
CREATE INDEX idx_product_variants_product_id ON product_variants(product_id);
CREATE INDEX idx_pricing_variant_id ON pricing(product_variant_id);
CREATE INDEX idx_stock_variant_id ON stock_inventory(product_variant_id);
CREATE INDEX idx_orders_ref ON orders(order_ref);
CREATE INDEX idx_orders_status ON orders(payment_status, order_status);
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_order_items_variant_id ON order_items(product_variant_id);

COMMIT;
