-- ============================================================
-- Migration 35: Admin Transactions module
-- Peer-to-peer transactions between admin users that require
-- recipient approval before they are considered confirmed.
-- ============================================================

CREATE TABLE admin_transactions (
    id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount               NUMBER(15, 2)   NOT NULL,
    currency             VARCHAR2(10)    DEFAULT 'SGD' NOT NULL,
    description          CLOB            NOT NULL,
    transaction_date     DATE            NOT NULL,
    -- Sender (admin_users.id or users.id depending on admin type)
    sender_id            NUMBER          NOT NULL,
    sender_admin_type    VARCHAR2(20)    DEFAULT 'legacy' NOT NULL,
    sender_name          VARCHAR2(150)   NOT NULL,
    -- Recipient
    recipient_id         NUMBER          NOT NULL,
    recipient_admin_type VARCHAR2(20)    DEFAULT 'legacy' NOT NULL,
    recipient_name       VARCHAR2(150)   NOT NULL,
    -- Approval workflow
    status               VARCHAR2(20)    DEFAULT 'pending' NOT NULL,
    approved_at          TIMESTAMP WITH TIME ZONE,
    rejection_reason     CLOB,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_admin_tx_sender    ON admin_transactions (sender_id, sender_admin_type);
CREATE INDEX idx_admin_tx_recipient ON admin_transactions (recipient_id, recipient_admin_type);
CREATE INDEX idx_admin_tx_status    ON admin_transactions (status);

COMMIT;
